import {projectPage, projectIndex, projectNavigation, aboutPage} from './project-views.js?v=51';
import {mountHeart, parkHeart, setHeartMotion} from './heart-media.js?v=51';
import {PERSONAL} from './personal.js?v=51';
import {PORTFOLIO as P} from './portfolio.js?v=51';
import {displayFor} from './display.js?v=51';
import {Workshop,anchors} from './scene.js?v=51';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let workshop,current=location.hash.slice(1)||'room',roomRoute='room',selected='project/1',trail=[],filter='All work',returnFocus=null,toastTimer=0;
const projects=P.projects,experiences=P.experiences;
function info(key){if(key.startsWith('project/'))return projects[+key.split('/')[1]];if(key.startsWith('experience/'))return experiences[+key.split('/')[1]];return null}
const labels={work:'Projects · Explore my work',experiences:'Experience · Where I’ve contributed',skills:'Skills · How I work',favorites:'My favorites · Movies, songs, activities and games','favorites/movies':'Favorite movies','favorites/songs':'Favorite songs','favorites/activities':'Favorite activities','favorites/games':'Favorite games','photo/baseball':'Baseball photo · Open favorite activities','photo/surfing':'Surfing photo · Open favorite activities','photo/hiking':'Hiking photo · Open favorite activities',hat:'Place the hat on Frosty',frosty:'Frosty · Select to remove or place his hat',tv:'Explore the selected project',about:'About Samuel Frausto',portrait:'Portrait of Samuel Frausto · Open About',firewood:'Add a log to the fire. You can also drag the wood into the hearth.'};
function label(key){const d=info(key);return d?(d.title||d.name)+' · '+d.role:labels[key]||''}
function notify(text){$('roomLabel').textContent=text;$('roomLabel').classList.toggle('visible',Boolean(text));clearTimeout(toastTimer);if(text)toastTimer=setTimeout(()=>$('roomLabel').classList.remove('visible'),5000)}
const channels=['project/1','project/4','project/6'];
function preview(key){
 if(!key?.match(/^(project|experience)\//))return;
 selected=key;const data=info(key),isExperience=key.startsWith('experience/'),display=displayFor(key,data);
 if(workshop)workshop.previewKey=key;workshop?.preview(display);
 $('playPreview').hidden=!display.src;
 $('tvScreen').classList.toggle('intro-screen',Boolean(display.intro));$('tvScreen').classList.toggle('research-screen',Boolean(display.inProgress));$('tvScreen').classList.toggle('heart-screen',Boolean(display.liveHeart));
 $('previewTitle').textContent=display.title;$('previewContext').textContent=display.eyebrow;$('previewDescription').textContent=display.description;$('mediaCaption').textContent=display.caption||'';
 $('channelNumber').textContent=channels.includes(key)?`${channels.indexOf(key)+1} / ${channels.length}`:'•';
 $('previewStory').textContent=isExperience?'Explore experience →':'Explore project →';
 $('tvImageLink').setAttribute('aria-label',`Open ${display.title}`);
 document.querySelectorAll('.shelf-label').forEach(b=>b.classList.toggle('selected',b.dataset.object===key));
 if(current==='room'){syncHeart();workshop?.autoPlayPreview();}
}
function syncHeart(){
 if(current==='room'&&selected==='project/1')mountHeart($('tvLive'),'tv');
 else if(current==='project/1')mountHeart($('heartStage'),'viewer');
 else parkHeart();
}
function select(key){clearTimeout(hoverTimer);if(key==='firewood'){workshop.feedFire();return}if(key==='portrait'){navigate('about');return}if(key.startsWith('photo/')){navigate('favorites/activities');return}if(key==='tv'){navigate(selected);return}if(key==='hat'||key==='frosty'){notify(workshop.wake(key==='hat'?true:undefined)?'Frosty is awake. Select him to remove the hat.':'Hat off. Frosty is resting.');return}if(info(key))preview(key);navigate(key)}
let hoverTimer;function hover(key){clearTimeout(hoverTimer);if(current!=='room'&&current!=='library')return;if(key){hoverTimer=setTimeout(()=>{if(current!=='room'&&current!=='library')return;preview(key);if(!objectLabels[key])notify(label(key))},180)}else notify('')}
const buttons=[];
const objectLabels={
 'experience/0':['Edwards','Intern / Contractor',''], 'experience/1':["B.S. Human-Technology<br>Interaction ’28",'Student',''], 'experience/2':['Jel Sert','Intern',''], 'experience/3':['UChicago','Fellowship Awardee',''],
 'project/1':['Alma','Interactive learning',''], 'project/4':['VR Baseball','Pitch prototype',''], 'project/6':['Cyberpunk twin','3D + pipeline tools',''], 'project/12':['Traffic twin','Research in progress','Now'],
 about:['About me','Samuel Frausto',''],firewood:['Feed the fire','',''],work:['Projects','What I made','01'],experiences:['Experience','Where I worked','02'],skills:['Skills','Tools & strengths','03'],favorites:['My favorites','',''],'favorites/movies':['Movies','',''],'favorites/songs':['Songs','',''],'favorites/activities':['Activities','',''],'favorites/games':['Games','','']};
for(const [key,anchor] of Object.entries(anchors)){if(key==='tv')continue;const b=document.createElement('button'),d=objectLabels[key],isBook=['work','experiences','skills'].includes(key),isPhoto=key.startsWith('photo/')||key==='portrait',isPersonal=key.startsWith('favorites')||key==='about';
 const size=isBook?[200,250]:key.startsWith('experience/')?[360,80]:key.startsWith('project/')?[240,74]:isPhoto?[180,265]:key==='firewood'?[210,30]:key==='about'?[360,55]:key==='favorites'?[300,40]:[260,36];
 b.className=isBook?'object-label book-label':isPhoto?'surface-label photo-label':d?'object-label surface-label '+(isPersonal?'library-label':'shelf-label'):'hot-object';b.setAttribute('aria-label',label(key));b.dataset.object=key;b.style.setProperty('--surface-width',size[0]+'px');b.style.setProperty('--surface-height',size[1]+'px');
 b.innerHTML=isPhoto?'':d?`${d[2]?`<em>${d[2]}</em>`:''}<strong>${d[0]}</strong>${d[1]?`<small>${d[1]}</small>`:''}<span class="open-mark">${isBook?'Open book ↗':'↗'}</span>`:'↗';
 b.onclick=()=>select(key);b.onpointerenter=()=>workshop?.setHover(key);b.onpointerleave=()=>workshop?.setHover(null);b.onfocus=()=>{hover(key);workshop?.setHover(key)};b.onblur=()=>workshop?.setHover(null);$(isBook?'bookAccess':'objectAccess').appendChild(b);buttons.push({b,key,anchor,isBook,d,size,isPhoto});}
// Map a rectangular DOM surface onto a projected plane: sharp, accessible text in the room.
function pinPlane(element,points,width,height){
 const [p0,p1,p2,p3]=points,dx1=p1.x-p2.x,dx2=p3.x-p2.x,dy1=p1.y-p2.y,dy2=p3.y-p2.y;
 const dx3=p0.x-p1.x+p2.x-p3.x,dy3=p0.y-p1.y+p2.y-p3.y,det=dx1*dy2-dx2*dy1;
 const g=(dx3*dy2-dx2*dy3)/det,h=(dx1*dy3-dx3*dy1)/det;
 const a=p1.x-p0.x+g*p1.x,b=p3.x-p0.x+h*p3.x,d=p1.y-p0.y+g*p1.y,e=p3.y-p0.y+h*p3.y;
 element.style.transform=`matrix3d(${a/width},${d/width},0,${g/width},${b/height},${e/height},0,${h/height},0,0,1,0,${p0.x},${p0.y},0,1)`;
}
function positionUI(scene){if(current!=='room'&&current!=='library')return;const rect=$('scene').getBoundingClientRect();$('objectAccess').style.clipPath=`inset(${rect.top}px ${innerWidth-rect.right}px ${innerHeight-rect.bottom}px ${rect.left}px)`;
 for(const {b,key,anchor,isBook,d,size,isPhoto} of buttons){
  const personal=key.startsWith('favorites')||key.startsWith('photo/')||['hat','frosty','about','portrait'].includes(key);b.hidden=(current==='library')!==personal||(key==='hat'&&scene.frosty);if(key==='frosty'){b.setAttribute('aria-label',scene.frosty?'Frosty · Remove his hat':'Frosty · Put on his hat');b.setAttribute('aria-pressed',String(scene.frosty));}if(b.hidden)continue;
  if(isBook&&innerWidth<=700)continue;
  const corners=isBook?scene.bookCorners(key):(d||isPhoto)?scene.surfaceCorners(key):null;
  if(corners){pinPlane(b,corners,...size);b.style.visibility=corners.some(p=>p.visible)?'visible':'hidden';continue;}
  const p=scene.project(anchor);b.style.left=p.x+'px';b.style.top=p.y+'px';b.style.visibility=p.visible?'visible':'hidden';
 }
 $('tvScreen').hidden=current==='library';const corners=scene.tvCorners();pinPlane($('tvScreen'),corners,640,360);$('tvScreen').style.visibility=corners.some(p=>p.visible)?'visible':'hidden';
}
function changeChannel(delta){preview(channels[(Math.max(0,channels.indexOf(selected))+delta+channels.length)%channels.length]);workshop?.spotlight(selected);}
$('previousPreview').onclick=()=>changeChannel(-1);$('nextPreview').onclick=()=>changeChannel(1);
$('playPreview').onclick=()=>workshop.playPreview();$('tvImageLink').onclick=()=>navigate(selected);$('visitPreview').onclick=()=>navigate('work');$('tvScreen').onpointerenter=()=>{workshop?.setHover('tv');workshop?.autoPlayPreview()};$('tvScreen').onpointerleave=()=>workshop?.setHover(null);
try{workshop=new Workshop($('scene'),{select,hover,notify,position:positionUI,ready:()=>{preview(selected);render(location.hash.slice(1)||'room');if(current==='room')workshop.spotlight(selected)},error:()=>document.body.classList.add('scene-failed')});preview(selected)}catch(e){document.body.classList.add('scene-failed');console.error(e);$('loadDetail').textContent='3D is unavailable in this browser. You can still explore the collection below.'}
function projectCard(p){return `<button class="project-card" data-project="${p.id}"><span class="image ${p.poster?'':'type-cover'}">${p.poster?`<img src="${p.poster}" alt="" loading="lazy" class="${p.mediaFit==='contain'?'contain-image':''}">`:esc(p.category)}</span><span class="card-body"><span class="role">${esc(p.role)}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><span class="more">${p.id===0||p.id===12?'Current work · In development':'See my contribution →'}</span></span></button>`}
function projectGrid(ids){return `<div class="project-grid">${ids.map(i=>projectCard(projects[i])).join('')}</div>`}
function workView(){return projectIndex(P,filter);}
function experienceView(){return `<span class="eyebrow">Full experience</span><h2>Where I’ve contributed.</h2><p class="lead">Clinical learning, spatial computing, research and brand communication. Each place asks something different of me.</p><div class="experience-grid">${experiences.map(e=>`<button class="experience-card" data-experience="${e.id}" style="--accent:${e.accent}"><img src="${e.logo}" alt="${esc(e.name)} logo"><span>${e.id===0?'<span class="current">Current · Contractor</span>':`<span class="eyebrow">${e.context}</span>`}<h3>${e.name}</h3><span class="role">${e.role}</span><p>${e.intro}</p><span class="more">Open full experience →</span></span></button>`).join('')}</div>`}
function capabilityView(){return `<span class="eyebrow">Skills</span><h2>What I can bring<br>to the next problem.</h2><p class="lead">Start with the kind of work you need. Open a skill group to see the tools behind it and the projects where I used them.</p><div class="capability-list">${P.capabilities.map((c,i)=>`<details class="capability" ${i===0?'open':''}><summary><h3>${c.title}</h3></summary><p>${c.summary}</p><div class="tool-tags">${c.skills.map(s=>`<span>${s}</span>`).join('')}</div><p>${c.example}</p><span class="eyebrow">See it in the work</span><div class="proof-links">${c.projects.map(id=>`<button data-project="${id}">${projects[id].title} ↗</button>`).join('')}</div></details>`).join('')}</div>`}
function personalView(category='movies'){
 const collection=PERSONAL[category]||PERSONAL.movies;
 const nav=`<nav class="personal-tabs" aria-label="Personal collections">${Object.entries(PERSONAL).map(([k,c])=>`<button data-route="favorites/${k}" aria-current="${k===category?'page':'false'}">${c.title.replace('Favorite ','')}</button>`).join('')}</nav>`;
 let body='';
 if(category==='activities')body=`<div class="activity-gallery">${collection.items.map(item=>`<figure><button class="activity-photo ${item.key}" data-photo="${item.key}" aria-label="Enlarge ${item.title.toLowerCase()} photo"><img src="${item.image}" alt="${item.alt}" loading="lazy"><span>View photo ↗</span></button><figcaption>${item.title}</figcaption></figure>`).join('')}</div>`;
 else if(category==='songs')body=`<ol class="record-list">${collection.items.map((item,i)=>`<li><a class="album-cover" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer" aria-label="Listen to ${esc(item.title)} by ${esc(item.by)}"><img src="${item.image}" alt="${esc(item.album)} album cover" loading="lazy"></a><span><small>0${i+1}</small><h3>${item.title}</h3><p>${item.by}</p><a class="collection-source" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">Listen ↗</a></span></li>`).join('')}</ol>`;
 else body=`<div class="cover-grid ${category}">${collection.items.map(item=>`<a class="cover-card" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer"><span class="cover-art"><img src="${item.image}" alt="${esc(item.title)} ${category==='movies'?'movie poster':'game artwork'}" loading="lazy"></span><h3>${item.title}</h3><span class="collection-source">${category==='movies'?'About the film':'About the game'} ↗</span></a>`).join('')}</div>`;
 return `<span class="eyebrow">Off the clock</span><h2>My favorites.</h2>${nav}<h3 class="collection-title">${collection.title}</h3>${body}`;
}
function aboutView(){return aboutPage();}
function showPhoto(key){const item=PERSONAL.activities.items.find(i=>i.key===key);if(!item)return;$('photoImage').src=item.image;$('photoImage').alt=item.alt;$('photoTitle').textContent=item.title;$('photoDialog').showModal();}
function projectStory(p){return projectPage(p);}
function experienceStory(e){return `<img class="experience-logo" src="${e.logo}" alt="${e.name} logo"><div class="story-header">${e.id===0?'<span class="current">Current · Contractor</span>':`<span class="eyebrow">${e.status}</span>`}<h2>${e.name}</h2><span class="role">${e.role}</span><p class="lead">${e.intro}</p></div>${e.poster?`<figure class="experience-media"><button class="media-enlarge" data-media-image="${esc(e.poster)}" data-media-caption="${esc(e.mediaCaption)}" aria-label="Enlarge ${esc(e.name)} project image"><img src="${e.poster}" alt="${esc(e.mediaCaption)}"><span>View image ↗</span></button><figcaption>${e.mediaCaption}</figcaption></figure>`:''}<h3 class="evidence-title">What I contributed</h3><ol class="contribution-list">${e.part.map(p=>`<li>${p}</li>`).join('')}</ol><p class="team-note">${e.note}</p><h3 class="evidence-title">${e.id===0?'Current work':'The work behind the experience'}</h3>${projectGrid(e.projects)}`}
function render(route){if(route==='books'||route==='favorites')route='favorites/movies';if(route==='projects')route='work';if(route==='capabilities')route='skills';if(!['room','library','about','work','experiences','skills'].includes(route)&&!/^favorites\/(movies|songs|activities|games)$/.test(route)&&!/^project\/(?:[0-9]|1[0-2])$/.test(route)&&!/^experience\/[0-3]$/.test(route))route='room';parkHeart();document.querySelectorAll('#readerContent video').forEach(v=>v.pause());current=route;if(info(route))preview(route);
 const open=!['room','library'].includes(route);if(!open)roomRoute=route;else if(route.startsWith('favorites/'))roomRoute='library';document.body.dataset.area=roomRoute;document.body.classList.toggle('reading',open);$('reader').hidden=!open;$('roomUI').inert=open;document.querySelector('.room-actions').inert=open;document.querySelector('.identity').inert=open;notify('');workshop?.focus(route);
 $('libraryToggle').setAttribute('aria-label',roomRoute==='library'?'Return to the workshop':'Learn more about me');$('libraryToggle').innerHTML=roomRoute==='library'?'<span>→</span><small>Back to my work</small><em>Return to the workshop</em>':'<span>←</span><small>About & favorites</small><em>Learn more about me</em>';
 $('libraryTabs').hidden=route!=='library';$('panControls').hidden=route==='library';
 if(!open){syncHeart();if(workshop?.ready)positionUI(workshop);if(returnFocus?.isConnected&&!returnFocus.hidden)returnFocus.focus({preventScroll:true});return;}
 $('close').textContent=roomRoute==='library'?'Back to library ×':'Return to room ×';$('back').disabled=trail.length===0;$('crumb').textContent=route==='about'?'About me':route.startsWith('favorites')?'Personal collection':route.startsWith('experience')?'Experience archive':route==='skills'?'Skills':'Project folio';document.querySelectorAll('.reader-nav [data-route]').forEach(b=>b.classList.toggle('active',route===b.dataset.route||route.startsWith(b.dataset.route==='work'?'project/':b.dataset.route==='experiences'?'experience/':'--')));
 let html='';if(route==='about')html=aboutView();else if(route==='work')html=workView();else if(route==='experiences')html=experienceView();else if(route==='skills')html=capabilityView();else if(route.startsWith('favorites/'))html=personalView(route.split('/')[1]);else if(route.startsWith('project/'))html=projectStory(projects[+route.split('/')[1]]);else html=experienceStory(experiences[+route.split('/')[1]]);
 const projectRoute=route==='work'||route.startsWith('project/');$('projectRail').hidden=!projectRoute;$('reader').classList.toggle('project-reader',projectRoute);$('projectRail').innerHTML=projectRoute?projectNavigation(P,route):'';
 $('readerContent').innerHTML=html;$('readerContent').querySelector('h2').id='readerTitle';$('readerContent').scrollTop=0;bindContent();syncHeart();$('reader').focus({preventScroll:true});
}
function navigate(route,add=true){if(route===current)return;if(['room','library'].includes(current))returnFocus=document.activeElement;else if(add&&!['room','library'].includes(route))trail.push(current);if(['room','library'].includes(route))trail=[];history.pushState({},'','#'+route);render(route);}
function bindContent(){document.querySelectorAll('[data-media-image]').forEach(b=>b.onclick=()=>{$('photoImage').src=b.dataset.mediaImage;$('photoImage').alt=b.dataset.mediaCaption;$('photoTitle').textContent=b.dataset.mediaCaption;$('photoDialog').showModal()});document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>showPhoto(b.dataset.photo));document.querySelectorAll('#reader [data-project]').forEach(b=>b.onclick=()=>navigate('project/'+b.dataset.project));document.querySelectorAll('#readerContent [data-experience]').forEach(b=>b.onclick=()=>navigate('experience/'+b.dataset.experience));document.querySelectorAll('#reader [data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render('work')});}

window.addEventListener('popstate',()=>{trail=[];render(location.hash.slice(1)||'room')});document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));$('close').onclick=()=>navigate(roomRoute);$('back').onclick=()=>navigate(trail.pop()||roomRoute,false);$('previewStory').onclick=()=>navigate(selected);document.querySelector('.identity a').onclick=e=>{e.preventDefault();navigate('room')};$('guide').onclick=()=>$('guideDialog').showModal();$('closeGuide').onclick=$('start').onclick=()=>$('guideDialog').close();$('panLeft').onclick=()=>workshop?.panBy(-2);$('panRight').onclick=()=>workshop?.panBy(2);$('centerRoom').onclick=()=>workshop?.center();$('libraryToggle').onclick=()=>navigate(current==='library'?'room':'library');$('portraitLink').onclick=()=>navigate('about');
let motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;function motionLabel(){$('motion').textContent=motion?'Motion on':'Motion paused';$('motion').setAttribute('aria-pressed',String(motion));workshop?.setMotion(motion);setHeartMotion(motion)}motionLabel();$('motion').onclick=()=>{motion=!motion;motionLabel()};matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{motion=!e.matches;motionLabel()});document.addEventListener('visibilitychange',()=>{if(document.hidden)workshop?.stopPreview();else if(['room','library'].includes(current))workshop?.setMotion(motion)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')workshop?.cancelDrag();if(e.key==='Escape'&&!$('guideDialog').open&&!$('photoDialog').open&&!['room','library'].includes(current))navigate(roomRoute);if(e.key==='Tab'&&!$('photoDialog').open&&!['room','library'].includes(current)){const all=[...$('reader').querySelectorAll('button:not(:disabled),a[href],summary')].filter(n=>n.getClientRects().length),first=all[0],last=all.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('reader'))){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
$('closePhoto').onclick=()=>$('photoDialog').close();
$('reader').setAttribute('role','dialog');$('reader').setAttribute('aria-modal','true');render(location.hash.slice(1)||'room');
