const cv='assets/Samuel_Frausto_Resume.pdf?v=20260910';
export function homePage(P){
 const cards=[1,4,6].map((id,i)=>{const p=P.projects[id];return `<button class="overview-project ${i===0?'overview-featured':''}" data-project="${id}"><span class="overview-image"><img src="${p.poster}" alt="" ${i?'loading="lazy"':''}><span>${id===1?'Interactive learning':'Watch the demo'} ↗</span></span><span class="overview-project-copy"><span class="eyebrow">0${i+1} / ${id===1?'Learning & interaction design':id===4?'Spatial prototyping':'3D & creative tools'}</span><h3>${id===1?'Alma':id===4?'VR Baseball':'Cyberpunk digital twin'} <span>↗</span></h3><p>${p.summary}</p><span class="overview-project-link">${id===1?'Explore the heart experience':'Open the project'} →</span></span></button>`}).join('');
 return `<a class="skip-link" href="#home/work" data-route="home/work">Skip to selected work</a>
 <header class="overview-header"><a class="overview-name" href="#home" data-route="home">Samuel Frausto<span>Design & creative technology</span></a><nav aria-label="Main navigation"><a href="#home/work" data-route="home/work">Work</a><a href="#home/about" data-route="home/about">About</a><a href="#home/experience" data-route="home/experience">Experience</a><a class="overview-cv" href="${cv}" target="_blank" rel="noopener noreferrer" aria-label="Full Experience + Project CV (PDF, new tab)">Full CV ↗</a></nav></header>
 <main class="overview-main">
 <section class="overview-hero" aria-labelledby="homeTitle"><div><span class="eyebrow">UX design + creative technology</span><h1 id="homeTitle" tabindex="-1">Hi, I’m Samuel.<br>I design things<br><em>you can explore.</em></h1><p>I’m a Human-Technology Interaction student at USC, currently creating learning experiences at Edwards Lifesciences.</p><a class="primary" href="#home/work" data-route="home/work">Start with my work <span>↓</span></a><a class="hero-about" href="#home/about" data-route="home/about">A little about me ↗</a></div><figure class="hero-portrait"><img src="assets/personal/portrait.jpg" alt="Samuel Frausto beneath a stone arcade"><figcaption><span>Samuel Frausto</span>Designer, student & maker.</figcaption></figure></section>
 <section class="overview-section" id="homeWork" aria-labelledby="homeWorkTitle"><header class="overview-section-head"><div><span class="eyebrow">01 / Selected work</span><h2 id="homeWorkTitle" tabindex="-1">Ideas you can get<br>your hands on.</h2></div><p>Interactive learning, spatial experiences, and the tools that bring them to life.</p></header>
 <div class="workshop-invitation"><div class="tv-symbol" aria-hidden="true"><span>SF</span><i></i></div><div><h3>Take a look around my workshop.</h3><p>A 3D room where the TV brings these projects to life. Choose a project, watch its preview, then explore the story.</p></div><a class="primary" href="#room" data-route="room">Enter the workshop <span>→</span></a></div>
 <div class="overview-projects">${cards}</div><button class="text-action" data-route="work">Browse all projects & experiments <span>→</span></button></section>
 <section class="overview-section overview-about" id="homeAbout" aria-labelledby="homeAboutTitle"><header class="overview-section-head"><div><span class="eyebrow">02 / About me</span><h2 id="homeAboutTitle" tabindex="-1">The person<br>behind the projects.</h2></div></header><div class="overview-about-grid"><div><p class="about-opening">I work at the intersection of design, technology, and learning.</p><p>At USC’s Iovine & Young Academy, I’m studying Human-Technology Interaction. At Edwards Lifesciences, I work on XR learning experiences.</p><p>For Alma, I thought through what someone needed to learn, what each section should show, and how they could interact with it. Then I used code, 3D tools, and AI to bring those decisions into a working experience.</p><button class="text-action" data-route="about">More about how I work <span>→</span></button></div><aside class="about-now"><span class="eyebrow">A little context</span><dl><div><dt>Studying</dt><dd>B.S. Human-Technology Interaction ’28<span>USC Iovine & Young Academy</span></dd></div><div><dt>Currently</dt><dd>XR Learning Design · Contractor<span>Edwards Lifesciences</span></dd></div><div><dt>Outside of work</dt><dd>Baseball, surfing & hiking.</dd></div></dl></aside></div><div class="outside-heading"><h3>When I step away from the screen.</h3><button class="text-action" data-route="library">Explore my favorites <span>↗</span></button></div><div class="overview-life">${[['baseball','Baseball'],['surfing','Surfing'],['hiking','Hiking']].map(([key,title])=>`<figure><button data-photo="${key}" aria-label="Enlarge ${key} photo"><img src="assets/personal/${key}.jpg" alt="Samuel ${key==='baseball'?'playing baseball':key}" loading="lazy"></button><figcaption>${title}</figcaption></figure>`).join('')}</div></section>
 <section class="overview-section" id="homeExperience" aria-labelledby="homeExperienceTitle"><header class="overview-section-head"><div><span class="eyebrow">03 / Experience</span><h2 id="homeExperienceTitle" tabindex="-1">Where I’m learning.<br>Where I’m contributing.</h2></div><a class="text-action" href="${cv}" target="_blank" rel="noopener noreferrer">Full Experience + Project CV <span>↗</span></a></header><div class="overview-experiences">${P.experiences.map(e=>`<button data-experience="${e.id}"><img src="${e.logo}" alt="" loading="lazy"><span><strong>${e.name}</strong><small>${e.role}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div></section>
 <footer class="overview-footer"><span class="eyebrow">Let’s make something worth exploring.</span><a href="mailto:samueljfrausto@gmail.com">Get in touch <span>↗</span></a><div><span>Samuel Frausto · Design & creative technology</span><a href="#home" data-route="home">Back to top ↑</a></div></footer></main>`;
}
