const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const featured=[1,4,6],order=[1,4,6,12,2,5,7,3,8,9,10,11,0];
const short={1:'Alma',4:'VR Baseball',6:'Cyberpunk Twin',12:'Traffic Twin',2:'IYH Digital Twin',5:'Pavilia',7:'Synesthesia',3:'SuzChews',8:'Pure Kick × Harley',9:'Fla-Vor-Ice × Crayola',10:'Jel Sert × Jamba',11:'TET2 Research',0:'XR Clinical Learning'};
const kinds={1:'Interactive learning',4:'Pitch simulation',6:'3D & workflow tools',12:'Research in progress'};
function thumb(p){return p.poster?`<img src="${esc(p.poster)}" alt="" loading="lazy" class="${p.mediaFit==='contain'?'contain-image':''}">`:`<span class="text-thumb">${p.id===12?'↗':esc(short[p.id].slice(0,2))}</span>`;}
export function projectNavigation(P,route){return `<button class="rail-all ${route==='work'?'active':''}" data-route="work" ${route==='work'?'aria-current="page"':''}>All projects <span>↗</span></button><p class="rail-label">Selected work</p>${featured.map(id=>rail(P.projects[id],route)).join('')}<details class="rail-more" ${/^project\//.test(route)&&!featured.includes(+route.split('/')[1])?'open':''}><summary>More projects</summary>${order.filter(id=>!featured.includes(id)).map(id=>rail(P.projects[id],route)).join('')}</details>`;}
function rail(p,route){return `<button class="rail-project ${route==='project/'+p.id?'active':''}" data-project="${p.id}" ${route==='project/'+p.id?'aria-current="page"':''}>${thumb(p)}<span><strong>${short[p.id]}</strong><small>${kinds[p.id]||p.category}</small></span></button>`;}
function tile(p,big=false){return `<button class="work-tile ${big?'lead-tile':''}" data-project="${p.id}"><span class="work-image">${thumb(p)}${p.id===1?'<span class="media-badge">Explore the beating heart ↗</span>':''}</span><span class="work-info"><span class="eyebrow">${kinds[p.id]||p.category}</span><h3>${p.title}<span aria-hidden="true">↗</span></h3><p>${p.summary}</p></span></button>`;}
export function projectIndex(P,filter){const items=order.map(id=>P.projects[id]).filter(p=>filter==='All work'||p.category===filter);return `<div class="work-heading"><span class="eyebrow">Selected work & experiments</span><h2>Ideas you can<br>get your hands on.</h2><p class="lead">Learning experiences, spatial prototypes, and the tools that make them work.</p></div><div class="filter-row" aria-label="Filter projects">${['All work','Spatial & XR','Health & research','Brand & communication'].map(f=>`<button data-filter="${f}" aria-pressed="${f===filter}" class="${f===filter?'active':''}">${f}</button>`).join('')}</div><div class="work-grid">${items.map((p,i)=>tile(p,i===0&&filter==='All work')).join('')}</div>`;}
function actions(p){return p.url?`<a class="primary" href="${p.url}" target="_blank" rel="noopener noreferrer">${p.live?'Try the full experience':'View original project'} ↗</a>`:`<span class="status-inline">${p.id===12?'USC directed research · In progress':'Current work · In development'}</span>`;}
function imageFigure(src,caption,alt=caption){return `<figure class="project-media still-media"><button class="media-enlarge" data-media-image="${esc(src)}" data-media-caption="${esc(caption)}" aria-label="Enlarge image: ${esc(alt)}"><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy"><span>View image ↗</span></button><figcaption>${esc(caption)}</figcaption></figure>`;}
function videoFigure(src,poster,caption){return `<figure class="project-media"><video controls muted playsinline preload="metadata" poster="${esc(poster)}" src="${esc(src)}" aria-label="${esc(caption)}"></video><figcaption>${esc(caption)}</figcaption></figure>`;}
function media(p){if(p.id===1)return `<figure class="project-media heart-media"><div id="heartStage"></div><figcaption>Live model using the original Alma simulation. Explore a beat, open the cutaway, or drag to turn.</figcaption></figure>`;
 if(p.video)return videoFigure(p.video,p.poster,p.mediaCaption);
 if(p.poster)return imageFigure(p.poster,p.mediaCaption||'Original project material.',p.title+' — '+(p.mediaCaption||'project image'));
 return `<div class="project-status"><span class="eyebrow">${p.id===12?'Research notebook':'Project overview'}</span><h3>${p.id===12?'A traffic system you can experiment with.':p.title}</h3><p>${p.id===12?'Building a controllable environment for studying coordinated autonomous vehicles. Experiments and results are still ahead.':p.summary}</p>${p.id===12?'<span>OpenUSD · Omniverse · Python</span>':''}</div>`;}
function gallery(p){return p.gallery?.length?`<section class="case-gallery" aria-label="More from ${esc(p.title)}"><span class="eyebrow">A closer look</span><div class="gallery-grid">${p.gallery.map(m=>m.kind==='video'?videoFigure(m.src,m.poster,m.caption):imageFigure(m.src,m.caption,m.alt)).join('')}</div></section>`:'';}
const heartDecisions=[
 ['Start with what someone needs to learn.','I organized the experience around one heartbeat. Each section has a specific lesson, something to look at, and a control that makes the concept tangible.','Chambers → valves → pressure → timing → one complete beat'],
 ['Make the control match the concept.','A circular dial made the four-valves lesson harder to read. I asked for a two-position switch so learners could compare which valves open and close.','One clear comparison, one clear action'],
 ['Let the heart explain itself.','I asked for visible liquid to show blood volume, and tighter framing to show the atrium squeezing. The motion and focus needed to point at the lesson.','Show the change where it happens'],
 ['Keep the first read short.','After reading the whole site, I cut back the dense explanations. Each section leads with a short introduction; longer explanations and control help stay available on demand.','A quick entry, with room to go deeper']
];
function heartBody(){return `<section class="case-section"><div class="section-kicker">01 / The learning problem</div><h3>A complex subject.<br>A clear starting point.</h3><p>Employees can work at Edwards without working directly with the heart. I wanted to give them an approachable way to learn what it does: see the anatomy, move through a heartbeat, and connect the motion to an explanation.</p></section><section class="case-section"><div class="section-kicker">02 / My design decisions</div><h3>Make each interaction<br>teach one thing.</h3><div class="decision-list">${heartDecisions.map(([title,body,note],i)=>`<article class="decision"><span class="decision-number">0${i+1}</span><div><h4>${title}</h4><p>${body}</p><span class="decision-note">${note}</span></div></article>`).join('')}</div></section><section class="case-section"><div class="section-kicker">03 / How I built it</div><h3>Direction, iteration,<br>and AI-assisted development.</h3><p>I directed the content, interactions, and visual presentation, using Claude Code extensively for implementation and debugging. I reviewed working versions, identified what was hard to understand, and shaped the next revision.</p><div class="process-line"><span>Plan the lesson</span><b>→</b><span>Build with AI</span><b>→</b><span>Try it</span><b>→</b><span>Refine</span></div><p>The purchased 3D4SCI model supplies the anatomy and original heartbeat poses. The application’s simulation controls those poses and synchronizes the heart with the diagrams.</p><details class="build-details"><summary>The tools behind the experience</summary><p>TypeScript and Three.js power the interactive site. GSAP handles transitions. Blender and Python scripts prepare the model, while Vite and Node.js support development. Vitest checks the simulation.</p></details></section><section class="case-section case-outcome"><div class="section-kicker">04 / The result</div><h3>A heartbeat you can explore.</h3><p>A working browser experience with a beating heart, hands-on controls, and a synchronized cardiac-cycle diagram. Early viewers responded positively. Formal learning outcomes have not been measured.</p><p class="source-note">Model and original heartbeat poses: 3D4SCI. Learning structure, interaction direction, and visual iteration: Samuel Frausto. Development supported by Claude Code.</p></section>`;}
export function projectPage(p){const idx=featured.indexOf(p.id),next=featured[(idx+1+featured.length)%featured.length];return `<article class="project-story"><div class="case-intro"><header class="case-header"><span class="eyebrow">${p.id===1?'Interaction design · Interactive learning':p.category}</span><h2>${p.title}</h2><p class="lead">${p.summary}</p></header>${media(p)}<div class="case-details"><div class="case-meta"><span><small>My role</small>${p.role}</span><span><small>${p.id===1?'Built for':'Format'}</small>${p.id===1?'Employees without a cardiac background':p.id===4?'Desktop prototype':p.id===12?'Research in progress':p.id===7?'visionOS prototype':p.id>=8&&p.id<=10?'Brand communication':p.id===11?'Research poster':'Interactive project'}</span></div><div class="story-actions">${actions(p)}</div></div></div>${p.id===1?heartBody():`<section class="case-section"><div class="section-kicker">01 / The idea</div><h3>What I set out to make.</h3><p>${p.brief}</p></section><section class="case-section"><div class="section-kicker">02 / My contribution</div><h3>Where I took it forward.</h3><ol class="contribution-list">${p.part.map(s=>`<li>${s}</li>`).join('')}</ol>${p.team?`<p class="team-note">${p.team}</p>`:''}</section>${gallery(p)}<section class="case-section case-outcome"><div class="section-kicker">03 / What came out of it</div><h3>${p.id===12?'The current research scope.':'The result, so far.'}</h3><p>${p.outcome}</p></section>`}<div class="case-tools"><span class="eyebrow">Tools & methods</span><div class="tool-tags">${p.tools.map(t=>`<span>${t}</span>`).join('')}</div></div><footer class="case-next"><button data-route="work">← All projects</button><button data-project="${next}">Next: ${short[next]} →</button></footer></article>`;}
export function aboutPage(){return `<div class="about-intro"><img class="about-portrait" src="assets/personal/portrait.jpg" alt="Samuel Frausto beneath a stone arcade"><div><span class="eyebrow">A little about me</span><h2>Hi, I’m Samuel.</h2><p class="lead">I design interactive experiences and use creative technology to bring them to life.</p></div></div><div class="about-story"><p>I’m studying Human-Technology Interaction at USC’s Iovine & Young Academy and currently work in XR learning design at Edwards Lifesciences.</p><p>With Alma, I wanted employees without a cardiac background to be able to see how the heart works. I shaped what each section teaches, how it shows the idea, and what someone can do with it. My focus was turning a complicated subject into something you can explore.</p><p>My projects move between learning, real-time 3D, and simulation. I work with code, 3D tools, and AI, and keep refining the experience by trying it and asking what could be clearer.</p><div class="about-facts"><p><strong>Currently</strong><br>XR Learning Design · Contractor<br>Edwards Lifesciences</p><p><strong>Studying</strong><br>B.S. Human-Technology Interaction ’28<br>USC Iovine & Young Academy</p></div><p>Outside of work, I play baseball, surf, and hike. My library is a small collection of the films, music, games, and places I keep coming back to.</p></div><div class="story-actions"><button class="primary" data-route="work">Explore my work →</button><button class="secondary" data-route="library">Visit my library</button><a class="secondary" href="mailto:samueljfrausto@gmail.com">Get in touch ↗</a></div>`;}
